### ISSUE TITLE
Origin header not present

### ISSUE THREAD

**Issue by ghenry** [cloudwebrtc/dart-sip-ua#103]
Hi,

On `0.2.2` I'm getting on our SIP Proxies:

```
Jul 16 22:45:19 /sbin/opensips[13809]: ERROR:proto_ws:ws_parse_req_handshake: Origin header not present!
Jul 16 22:45:19 /sbin/opensips[13809]: ERROR:proto_ws:ws_read_req: cannot complete WebSocket handshake
```
On an `ngrep` I see this coming in:

```
GET /ws HTTP/1.1
user-agent: Dart/2.8 (dart:io)
connection: Upgrade
accept-encoding: gzip
content-length: 0
sec-websocket-version: 13
host: xxx.xxx.xxx.xxx
sec-websocket-key: 8odqnq6p8j4=
sec-websocket-protocol: sip
upgrade: websocket
```

**Comment by ghenry** [comment]
How do I change this `user-agent` too for the HTTP request for logging?

**Comment by ghenry** [comment]
Just testing with WS, not WSS at the moment.

**Comment by ghenry** [comment]
Here's the requirement in the OpenSIPS source:

https://github.com/OpenSIPS/opensips/blob/master/modules/proto_ws/ws_handshake_common.h#L978

I guess they presume it should always be there as it's a Browser connecting?

**Comment by ghenry** [comment]
I think this should be something that can be controlled on the client side?

https://tools.ietf.org/html/rfc6455#section-1.2

**Comment by cloudwebrtc** [comment]
@ghenry Looks like you need a custom header.

```dart
UaSettings settings = UaSettings();

...

settings.webSocketExtraHeaders = {
     'Origin': 'https://tryit.jssip.net', /// <- Change to your domain.
     'Host':'tryit.jssip.net:10443'
   };

...
```

**Comment by cloudwebrtc** [comment]
> How do I change this `user-agent` too for the HTTP request for logging?

The user-agent header in the HTTP Client seems to modify the dart HTTP client parameters.

https://github.com/cloudwebrtc/dart-sip-ua/blob/master/lib/src/transports/websocket_dart_impl.dart#L70

```dart
      var securityContext = new SecurityContext();
      var client = HttpClient(context: securityContext);

      client.userAgent = 'Other Name~'; /// <--- Here

```

**Comment by ghenry** [comment]
Of course! I have some extra headers set already and didn't think of faking it. Now doing:

`      'Origin': _packageInfo.packageName,
`

I'll try the userAgent bit before closing off completely. Thanks!

**Comment by ghenry** [comment]
> > How do I change this `user-agent` too for the HTTP request for logging?
> 
> The user-agent header in the HTTP Client seems to modify the dart HTTP client parameters.
> 
> https://github.com/cloudwebrtc/dart-sip-ua/blob/master/lib/src/transports/websocket_dart_impl.dart#L70
> 
> ```dart
>       var securityContext = new SecurityContext();
>       var client = HttpClient(context: securityContext);
> 
>       client.userAgent = 'Other Name~'; /// <--- Here
> ```

Where would I set that when using the example in this repo?

**Comment by cloudwebrtc** [comment]
Is it necessary to expose the parameters here? Because sip UA also has a `Settings.user_agent` the field in the SIP message.

https://github.com/cloudwebrtc/dart-sip-ua/blob/master/lib/src/config.dart#L26

If necessary, we can create an optional `webSocketUserAgent` and merge it with `webSocketExtraHeaders` into 
`Settings.webSocketSettings`.

**Comment by ghenry** [comment]
That would be great.
