### ISSUE TITLE
Codes for INVITE 

### ISSUE THREAD

**Issue by ghenry** [cloudwebrtc/dart-sip-ua#104]
Is there an option to set this as I can't see it?

Thanks.

**Comment by cloudwebrtc** [comment]
Hi, @ghenry I don’t quite understand, do you mean the codec sorting in INVITE SDP? Or does it add a custom header to the INVITE message?

**Comment by ghenry** [comment]
The codec list in the SDP, correct. 

Debug doesn't show th SDP offer, just says bundle. I'll check again though, but I cam always see it on a proper SIP trace server side if needed.

**Comment by ghenry** [comment]
Misunderstanding my side. Closing.
