### ISSUE TITLE
Unable to RTCPeerConnection::setRemoteDescription: SessionDescription is NULL.

### ISSUE THREAD

**Issue by huynhphu-pufu** [cloudwebrtc/dart-sip-ua#112]
Hello Admins, I am trying your example to connect to my server. I registered account and I can execute a call to another account in my server. But, when I click 'Accept' button to accept the phone, the example's code is breakdown and catch an exception. The exception message is `Unable to RTCPeerConnection::setRemoteDescription: SessionDescription is NULL.`. However, RTCSessionDescription var `offer` is not NULL, `var offer = new RTCSessionDescription(request.body, 'offer');` with request.body is sdp string (bellow this description). So, can you help me find the reason for this issue? Thank you.

SDP string:
```
v=0
o=root XXXXXXX428 XXXXXXX428 IN IP4 XXX.XX.XX.XX
s=Asterisk PBX 13.22.0
c=IN IP4 XXX.XX.XX.XX
t=0 0
m=audio 17644 RTP/SAVP 0 3 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:3 GSM/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 
a=rtcp-mux
a=sendrecv
```
![image](https://user-images.githubusercontent.com/25612479/90331545-8e84f280-dfdf-11ea-98c7-fa8786c3acd2.png)

p/s: I used Wave Lite app in iPhone X for the phone to Samsung SM-G5510

**Comment by cloudwebrtc** [comment]
@huynhphu-pufu Your SDP is not a WebRTC compatible SDP. The correct one should be SAVPF instead of SAVP. It needs to contain information such as ice info and RTCP-FB.

**Comment by kondori-reza1990** [comment]
@cloudwebrtc
hello
I use your library in my project but when i want answer to call, accure an exception.

Exception:
`D/FlutterWebRTCPlugin(10694): onConnectionChangeCLOSED
I/flutter (10694): [2022-02-08 14:49:23.344] Level.debug sip_ua_helper.dart:214 ::: call failed with cause: Code: [488], Cause: WebRTC Error, Reason: SetRemoteDescription(offer) failed
I/flutter (10694): [2022-02-08 14:49:23.365] Level.error rtc_session.dart:664 ::: emit "peerconnection:setremotedescriptionfailed" [error:Unable to RTCPeerConnection::setRemoteDescription: peerConnectionSetRemoteDescription(): WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: SessionDescription is NULL.]
E/flutter (10694): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Assertion failed: "peerconnection.setRemoteDescription() failed"
E/flutter (10694): #0      RTCSession.answer (package:voip_demo/sip_ua/src/rtc_session.dart:667:7)
E/flutter (10694): <asynchronous suspension>
E/flutter (10694): 
I/flutter (10694): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (10694): │ #0   SIPUAHelper._notifyCallStateListeners (package:voip_demo/sip_ua/src/sip_ua_helper.dart:361:14)
I/flutter (10694): │ #1   SIPUAHelper._options.<anonymous closure>.<anonymous closure> (package:voip_demo/sip_ua/src/sip_ua_helper.dart:264:9)
I/flutter (10694): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (10694): │ ⛔ Call 9621299f-9ed7-4754-be2b-4af5fbbfc7acac7e7068-2ed2-4b2b-84af-6852e561bd42 not found!
I/flutter (10694): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────`

my request body:
- [v=0
o=- 1230774591 1230774591 IN IP4 185.112.39.178
s=Asterisk
c=IN IP4 185.112.39.178
t=0 0
a=msid-semantic:WMS *
a=group:BUNDLE audio-0
m=audio 16558 UDP/TLS/RTP/SAVPF 107 0 101
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 6E:FC:3A:77:ED:1E:BC:0E:69:E3:05:D7:B2:BB:52:F8:52:F9:59:99:25:A7:FA:0B:F7:60:36:40:F8:BD:4E:B6
a=ice-ufrag:1f6bc8337a7662c33901ac0122cefcee
a=ice-pwd:53999123244c1c2f0ac5be7209068cad
a=candidate:Hb97027b2 1 UDP 2130706431 185.112.39.178 16558 typ host
a=candidate:Ha6e972cc 1 UDP 2130706431 fe80::20c:29ff:fec4:27ef 16558 typ host
a=rtpmap:107 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:60
a=sendrecv
a=rtcp-mux
a=ssrc:538394923 cname:c4f0d7e3-3049-4f04-8778-83d49175c566
a=msid:5295fc9f-49c1-40b6-a33b-3af767c15ff5 4032ab40-17d1-44c1-aa63-683199af1056
a=rtcp-fb:* transport-cc
a=mid:audi ] 

please help me.
thank you.
