### ISSUE TITLE
Release 0.2.3

### ISSUE THREAD

**Issue by ghenry** [cloudwebrtc/dart-sip-ua#113]
Could we get this out to have websocket headers exposed?

Thanks.

**Comment by cloudwebrtc** [comment]
Fixed.
https://github.com/cloudwebrtc/dart-sip-ua/releases/tag/0.2.3

**Comment by jbg** [comment]
Would you consider following pub's versioning policy? There have been several incompatible releases made as patch releases (0.2.x) causing breakage in projects that depend on this package.

**Comment by ghenry** [comment]
Could you expand on what those breakages were/are?

Thanks.

**Comment by jbg** [comment]
Most recent example was the introduction of the Call class and the moving of various methods and properties from SIPUAHelper to that new class. I think that was done in 0.2.2, which should therefore have been 0.3.0 according to pub's version policy since they were non-backwards-compatible changes.

**Comment by ghenry** [comment]
That makes sense. Yes, please open a new issue.

Out of interest, what are you using this project for and what app if public? 

Great to see it being depended on and apologies for any extra work caused.

I sponsored the development of this project and I'm amazed to see how quickly it's grown and the global usages.
