### ISSUE TITLE
Issue with Secure Web Sockets

### ISSUE THREAD

**Issue by rlsutton1** [cloudwebrtc/dart-sip-ua#15]
When initiating a call there is a sizable delay (up to 15 seconds).

I suspect this is a bug in the Asterisk Secure Web Sockets (WSS) handling, but if someone not using asterisk could test and check this issue with WSS would be appreciated so I can eliminate Dart as the possible source.

**Comment by cloudwebrtc** [comment]
@rlsutton1 We have already ported the main functions, we can perform interactive verification of common open-source servers, if the problems you encounter still exist, I think I can help solve them together.

**Comment by rlsutton1** [comment]
I have raised an issue with asterisk, so I'll close this issue until I hear back from them.
