### ISSUE TITLE
Port progress for v1.0.0

### ISSUE THREAD

**Issue by cloudwebrtc** [cloudwebrtc/dart-sip-ua#2]
Current progress:
- [x] Basic unit test
- [x] Integrated with flutter-webrtc
- [x] Register/Un-Register
- [x] Send Invite
- [x] Recv Invite
- [x] Hold/Unhold
- [ ] Dtmf send/recv
- [ ] Refer (Call Transfer)
- [ ] Message send/recv
- [ ] Re-Invite (audio/video call switch)
- [ ] Full-featured demo (android/ios flutter app)

**Comment by ghenry** [comment]
Looks good! Transfer?

**Comment by cloudwebrtc** [comment]
Yes, Transfer (Refer) will be supported.

**Comment by ghenry** [comment]
Of course. That's the proper term. Thanks.
