### ISSUE TITLE
Current work 

### ISSUE THREAD

**Issue by rlsutton1** [cloudwebrtc/dart-sip-ua#24]
Thought I should let you know what I'm working on. 

I feel that sip_ua_ helper belongs in the main lib, not the example and that there is far to much of the libs internals exposed through it. So I am currently working on moving it and exposing the information that clients will need without exposing the sip stack internals. I'm also changing the messaging between sip _ua_ helper and the example code to use a simple listener mechanism rather than the event manager. 

I found an existing  bug and have a fox for it where the Web socket doesn't close when stopping the sip stack. 

On Monday I'm intending to fix the dtmf code. It currently breaks after a single dmf digit.

**Comment by cloudwebrtc** [comment]
Sorry, I am busy with other things recently and can return to normal schedule next week.

Please refer to https://github.com/cloudwebrtc/dart-sip-ua/projects/1 for the progress of project v1.0.
I have a few thoughts on development work:
1, separate internal events and public events, try to make `package:sip_ua/sip_ua.dart` export the least public API file.
In the end, there is no SipMessage, Request, and signaling-related classes in the public API, but only some `required ua events,`, `status_code`, `cause`, `text message`, `error reason`, `MediaStream`, etc.
2. Discuss whether SIPUAHelper can be merged into lib, which makes it easier to develop UI with flutter.
3, as mentioned in projects v1.0, we need to conduct interactive tests (registration, call, DTMF, hold, re-invite, update, etc.) on some common open-source `sip server`.
4, for some of the necessary configuration APIs for export, for example, `Authentication User`, `stun/turn server`.

**Comment by rlsutton1** [comment]
If you wish to see what I've been working on with regard to Sip_ua_helper, have a look at https://github.com/noojee/dart-sip-ua

Otherwise, once the outstanding PR's are merged I'll be able to make a clean PR for these changes and we can review it then.

**Comment by cloudwebrtc** [comment]
I looked at the differences in your master repository, very good, exactly what I want.
