### ISSUE TITLE
Error running Gradle In example folder

### ISSUE THREAD

**Issue by patboyrico** [cloudwebrtc/dart-sip-ua#33]
After running the shell create command I get an error on running the flutter run command
`* Error running Gradle:
ProcessException: Process "C:\FlutterApps\dart-sip-ua\example\android\gradlew.bat" exited abnormally:
Configure project :flutter_webrtc
cache resource-at-url.bin (C:\Users\A4mation\.gradle\caches\modules-2\metadata-2.63\resource-at-url.bin) is   
corrupt. Discarding.
`
How do I get it working?

**Comment by cloudwebrtc** [comment]
Currently not tested under Windows, you can try running 
`flutter create --project-name sip_ua_example --org com.github.cloudwebrtc .`
in the example directory.

And add permission labels to `example/android/app/src/main/AndroidManifest.xml`.
```xml
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**Comment by patboyrico** [comment]
So i tried running that but I get am error which says .com.github.cloudwebrtc is not a valid dart package name
