### ISSUE TITLE
How can I connect to webrtc server ?

### ISSUE THREAD

**Issue by olegshentz1** [cloudwebrtc/dart-sip-ua#37]
I try to connect to webrtc server but client try to connect using ws and not webtc? 

> I/flutter (17329): [2019-12-03 13:41:05.713] Level.debug websocket_interface.dart:32 ::: new() [url:wss://kam13.x2one.com:8443/webrtc]
I/flutter (17329): [2019-12-03 13:41:06.96] Level.debug websocket_interface.dart:44 ::: SIP URI: sip:kam13.x2one.com:8443;transport=ws
I/flutter (17329): [2019-12-03 13:41:06.114] Level.debug ua.dart:103 ::: new() [configuration:Instance of 'Settings']
I/flutter (17329): [38;5;12m[2019-12-03 13:41:06.143] Level.info config.dart:246 ::: Check mandatory parameter => sockets.[0m
I/flutter (17329): [38;5;12m[2019-12-03 13:41:06.237] Level.info config.dart:246 ::: Check mandatory parameter => uri.[0m
I/flutter (17329): [2019-12-03 13:41:06.261] Level.debug config.dart:252 ::: Check optional parameter => authorization_user.
I/flutter (17329): [2019-12-03 13:41:06.308] Level.debug config.dart:252 ::: Check optional parameter => user_agent.
I/flutter (17329): [2019-12-03 13:41:06.331] Level.debug config.dart:252 ::: Check optional parameter => connection_recovery_max_interval.
I/flutter (17329): [2019-12-03 13:41:06.350] Level.debug config.dart:252 ::: Check optional parameter => connection_recovery_min_interval.
I/flutter (17329): [2019-12-03 13:41:06.369] Level.debug config.dart:252 ::: Check optional parameter => contact_uri.
I/flutter (17329): [2019-12-03 13:41:06.385] Level.debug config.dart:252 ::: Check optional parameter => display_name.
I/flutter (17329): [2019-12-03 13:41:06.400] Level.debug config.dart:252 ::: Check optional parameter => instance_id.
I/flutter (17329): [2019-12-03 13:41:06.410] Level.debug config.dart:252 ::: Check optional parameter => no_answer_timeout.
I/flutter (17329): [2019-12-03 13:41:06.419] Level.debug config.dart:252 ::: Check optional parameter => session_timers.
I/flutter (17329): [2019-12-03 13:41:06.428] Level.debug config.dart:252 ::: Check optional parameter => session_timers_refresh_method.
I/flutter (17329): [2019-12-03 13:41:06.437] Level.debug config.dart:252 ::: Check optional parameter => password.
I/flutter (17329): [2019-12-03 13:41:06.447] Level.debug config.dart:252 ::: Check optional parameter => realm.
I/flutter (17329): [2019-12-03 13:41:06.456] Level.debug config.dart:252 ::: Check optional parameter => ha1.
I/flutter (17329): [2019-12-03 13:41:06.464] Level.debug config.dart:252 ::: Check optional parameter => register.
I/flutter (17329): [2019-12-03 13:41:06.472] Level.debug config.dart:252 ::: Check optional parameter => register_expires.
I/flutter (17329): [2019-12-03 13:41:06.480] Level.debug config.dart:252 ::: Check optional parameter => registrar_server.
I/flutter (17329): [2019-12-03 13:41:06.488] Level.debug config.dart:252 ::: Check optional parameter => use_preloaded_route.
I/flutter (17329): [2019-12-03 13:41:06.537] Level.debug transport.dart:53 ::: new()
I/flutter (17329): [2019-12-03 13:41:06.582] Level.debug ua.dart:163 ::: start()
I/flutter (17329): [2019-12-03 13:41:06.590] Level.debug transport.dart:111 ::: connect()
I/flutter (17329): [2019-12-03 13:41:06.600] Level.debug ua.dart:844 ::: Transport connecting
I/flutter (17329): [2019-12-03 13:41:06.610] Level.debug sip_ua_helper.dart:146 ::: connecting => Instance of 'EventSocketConnecting'
I/flutter (17329): [2019-12-03 13:41:06.627] Level.debug websocket_interface.dart:104 ::: connect()
I/flutter (17329): [2019-12-03 13:41:06.635] Level.debug websocket_interface.dart:115 ::: connecting to WebSocket wss://kam13.x2one.com:8443/webrtc
I/flutter (17329): Allow self-signed certificate => kam13.x2one.com:8443. 
I/flutter (17329): [2019-12-03 13:41:07.533] Level.debug websocket_interface.dart:137 ::: Web Socket is now connected
I/flutter (17329): [2019-12-03 13:41:07.540] Level.debug websocket_interface.dart:200 ::: WebSocket wss://kam13.x2one.com:8443/webrtc connected
I/flutter (17329): [2019-12-03 13:41:07.550] Level.debug ua.dart:850 ::: Transport connected
I/flutter (17329): [2019-12-03 13:41:07.558] Level.debug sip_ua_helper.dart:152 ::: connected => Instance of 'EventSocketConnected'
I/flutter (17329): [38;5;208m[2019-12-03 13:41:07.573] Level.warning registrator.dart:114 ::: <sip:vt6bbpae@m423805m4506.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:df521cf6-9cef-4b89-ad61-3ba71fbd7fb7>"[0m
I/flutter (17329): [2019-12-03 13:41:07.629] Level.debug transport.dart:167 ::: send()
I/flutter (17329): [2019-12-03 13:41:07.644] Level.debug transport.dart:178 ::: sending message:
I/flutter (17329): 
I/flutter (17329): REGISTER sip:kam13.x2one.com SIP/2.0
I/flutter (17329): Via: SIP/2.0/WSS m423805m4506.invalid;branch=z9hG4bK1472475262
I/flutter (17329): Max-Forwards: 69
I/flutter (17329): To: <sip:rzPqcJYZgzb0eN1hz@kam13.x2one.com>
I/flutter (17329): From: "rzPqcJYZgzb0eN1hz" <sip:rzPqcJYZgzb0eN1hz@kam13.x2one.com>;tag=1g834w0a58
I/flutter (17329): Call-ID: 3568x3768761081i071641
I/flutter (17329): CSeq: 1 REGISTER
I/flutter (17329): Contact: <sip:vt6bbpae@m423805m4506.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:df521cf6-9cef-4b89-ad61-3ba71fbd7fb7>";expires=600
I/flutter (17329): Expires: 600
I/flutter (17329): Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
I/flutter (17329): Supported: path,gruu,outbound
I/flutter (17329): User-Agent: dart-sip-ua v0.0.1
I/flutter (17329): Content-Length: 0
I/flutter (17329): 
I/flutter (17329): 
I/flutter (17329): [2019-12-03 13:41:07.653] Level.debug websocket_interface.dart:165 ::: send()
I/flutter (17329): [2019-12-03 13:41:07.734] Level.debug websocket_interface.dart:130 ::: Closed by server [1002, null]!
I/flutter (17329): [2019-12-03 13:41:07.743] Level.debug websocket_interface.dart:205 ::: WebSocket wss://kam13.x2one.com:8443/webrtc closed
I/flutter (17329): [2019-12-03 13:41:07.757] Level.debug non_invite_client.dart:52 ::: transport error occurred, deleting transaction z9hG4bK1472475262
I/flutter (17329): [38;5;196m[2019-12-03 13:41:07.795] Level.error event_manager.dart:115 ::: NoSuchMethodError: The getter 'cause' was called on null.
I/flutter (17329): Receiver: null
I/flutter (17329): Tried calling: cause[0m
I/flutter (17329): [38;5;196m#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (17329): #1      UA.registrationFailed (package:sip_ua/src/ua.dart:497:29)
I/flutter (17329): #2      Registrator._registrationFailure (package:sip_ua/src/registrator.dart:348:14)
I/flutter (17329): #3      Registrator.register.<anonymous closure> (package:sip_ua/src/registrator.dart:134:12)
I/flutter (17329): #4      EventManager.emit.<anonymous closure> (package:sip_ua/src/event_manager/event_manager.dart:113:17)
I/flutter (17329): #5      List.forEach (dart:core-patch/growable_array.dart:283:8)
I/flutter (17329): #6      EventManager.emit (package:sip_ua/src/event_manager/event_manager.dart:110:12)
I/flutter (17329): #7      RequestSender.send.<anonymous closure> (package:sip_ua/src/request_sender.dart:53:27)
I/flutter (17329): #8      EventManager.emit.<anonymous closure> (package:sip_ua/src/event_manager/event_manager.dart:113:17)
I/flutter (17329): #9      List.forEach (dart:core-patch/growable_array.dart:283:8)
I/flutter (17329): #10     EventManager.emit (package:sip_ua/src/event_manager/event_manager.dart:110:12)
I/flutter (17329): #11     NonInviteClientTransaction.onTransportError (package:sip_ua/src/transactions/
I/flutter (17329): [2019-12-03 13:41:07.807] Level.debug sip_ua_helper.dart:158 ::: disconnected => Code: [1002], Cause: error, Reason: null
I/flutter (17329): [2019-12-03 13:41:07.819] Level.debug transport.dart:206 ::: reconnection attempt: 1. next connection attempt in 2 seconds

**Comment by cloudwebrtc** [comment]
@olegshentz1 I'm not sure where your problem lies. Are you connected to a SIP server that supports WSS Transport?
If so, from the log, you need to check why your server rejected the REGISTER signaling after the WebSocket connection was successful.
