### ISSUE TITLE
flutter desktop support?

### ISSUE THREAD

**Issue by ghenry** [cloudwebrtc/dart-sip-ua#4]
Looks like it?

**Comment by ghenry** [comment]
```
~/src/dart-sip-ua/example [master*]$ flutter devices
2 connected devices:

SM G970F • RF8M226YLZR • android-arm64 • Android 9 (API 28)
Linux    • Linux       • linux-x64     • Linux

~/src/dart-sip-ua/example [master*]$ flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Build process failed
make: *** No targets specified and no makefile found.  Stop.```

**Comment by cloudwebrtc** [comment]
In fact, the desktop version can be supported, but the flutter-webrtc plugin dependence on the texture API of flutter/engine. Texture PR I have submitted but still review, I can compile flutter/engine to get the demo program, but the compilation process is very complicated.

Flutter-webrtc for desktop:
Https://github.com/cloudwebrtc/flutter-webrtc/issues/119

Flutter-webrtc for web:
Https://github.com/cloudwebrtc/flutter-webrtc/issues/85

**Comment by cloudwebrtc** [comment]
![image](https://user-images.githubusercontent.com/17733746/66880485-b25d5d80-eff5-11e9-9165-3d5c60b679c9.png)
![image](https://user-images.githubusercontent.com/17733746/66880515-cbfea500-eff5-11e9-98df-be9f8adceed8.png)

**Comment by ghenry** [comment]
Nice!
