### ISSUE TITLE
UaSettings start function not working, getting error in android device and emulator also

### ISSUE THREAD

**Issue by maheshlalu** [cloudwebrtc/dart-sip-ua#40]
Level.error websocket_interface.dart:104 ::: NoSuchMethodError: The getter 'closeCode' was called on null.

**Comment by cloudwebrtc** [comment]
Can provide more logs？

**Comment by maheshlalu** [comment]
[2019-12-26 19:08:02.908] Level.info websocket_dart_impl.dart:21 ::: connect wss://devproxy01.buniapp.com:443/ws, {Sec-WebSocket-Protocol: sip}, null
I/flutter (10480): [2019-12-26 19:08:08.157] Level.error websocket_interface.dart:104 ::: NoSuchMethodError: The getter 'closeCode' was called on null.
I/flutter (10480): Receiver: null
I/flutter (10480): Tried calling: closeCode
I/flutter (10480): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (10480): #1      WebSocketImpl.connect (package:sip_ua/src/websocket_dart_impl.dart:37:28)
I/flutter (10480): <asynchronous suspension>
I/flutter (10480): #2      WebSocketInterface.connect (package:sip_ua/src/websocket_interface.dart:99:22)
I/flutter (10480): #3      Transport.connect (package:sip_ua/src/transport.dart:132:19)
I/flutter (10480): #4      UA.start (package:sip_ua/src/ua.dart:166:23)
I/flutter (10480): #5      SIPUAHelper.start (package:sip_ua/src/sip_ua_helper.dart:197:16)
I/flutter (10480): #6      _SIPRegisterState.registrationProcess (package:sipcalling/registerAccount.dart:139:12)
I/flutter (10480): #7      _SIPRegisterState._handleSave (package:sipcalling/registerAccount.dart:114:4)
I/flutter (10480): #8      _SIPRegisterState.buildRegisterBody.<anonymous closure> (package:sipcalling/registerAccount.dart:317:36)
I/flutter (10480): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
I/flutter (10480): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
I/flutter (10480): #11     GestureRecognizer.invokeCallback (package:flutter/src/gest
I/flutter (10480): [2019-12-26 19:08:08.160] Level.error websocket_interface.dart:178 ::: WebSocket wss://devproxy01.buniapp.com:443/ws error: NoSuchMethodError: The getter 'closeCode' was called on null.
I/flutter (10480): Receiver: null
I/flutter (10480): Tried calling: closeCode



NOTE: Same code working in iOS  but not working in Android.

**Comment by maheshlalu** [comment]
Got socket connection failed in Android but in iOS working good. below method called when socket is connected
      this.onClose(_socket.closeCode, _socket.closeReason);

**Comment by cloudwebrtc** [comment]
Looks like a bug.

**Comment by maheshlalu** [comment]
@cloudwebrtc please update on this.

**Comment by maheshlalu** [comment]
@cloudwebrtc please update

**Comment by maheshlalu** [comment]
I am getting same error in Android. @cloudwebrtc please update on it.

**Comment by maheshlalu** [comment]
CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))

**Comment by chikondot** [comment]
Hello, I am facing the exact same problem with my android emulator. Was the problem fixed? and if so my someone please assist
