### ISSUE TITLE
激活后，服务后台看到连接是WS，怎么变成wss

### ISSUE THREAD

**Issue by stoneLee81** [cloudwebrtc/dart-sip-ua#44]
日志截取 
CSeq: 4 REGISTER
I/flutter (18415): Contact: <sip:n235547h@j1e17518m12n.invalid;transport=ws>;+sip.ice;+sip.instance="<urn:uuid:abf5b8a7-3e40-47ec-b7f4-bb439ab2ad5e>";expires=60;reg-id=1
I/flutter (18415): Expires: 60
I/flutter (18415): Content-Length: 0

**Comment by cloudwebrtc** [comment]
如果您注册使用的是wss，而这里显示的是ws，则可能是bug.

**Comment by stoneLee81** [comment]
注册的是wss

**Comment by stoneLee81** [comment]
![image](https://user-images.githubusercontent.com/18001708/71614095-c7a15b80-2be4-11ea-8611-d6293eeb0f6e.png)

**Comment by cloudwebrtc** [comment]
应该是bug
