### ISSUE TITLE
App closes on helper.call

### ISSUE THREAD

**Issue by stuartkuentzel** [cloudwebrtc/dart-sip-ua#45]
When trying to start a call, the app is crashing and not returning any meaningful error.

<img width="928" alt="Screen Shot 2019-12-31 at 8 34 57 PM" src="https://user-images.githubusercontent.com/11183054/71620429-588c2d00-2c0d-11ea-99de-9770f73ef1a6.png">

I am running `_helper.call(handle, true);`. It looks like it is starting, but crashing when trying to start a new newRTCSession. Register state looks good, returning `RegristrationStateEnum.REGISTERED`. Building for iOS and running on an iPhone. Has anyone else run into this issue and know how to resolve it?

**Comment by cloudwebrtc** [comment]
You can try to run it with Xcode or Android Studio and see if there are native errors, for example, permission labels not added.

**Comment by stuartkuentzel** [comment]
Thanks for pointing me in the right direction. I ran it in Xcode and got the following error message...

`This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.`

The issue was resolved by adding to `ios/Runner/Info.plist`... 
```
<key>NSMicrophoneUsageDescription</key>
<string>We need your mic!</string>
```
