### ISSUE TITLE
emit "peerconnection:setremotedescriptionfailed" [error:Unable to RTCPeerConnection::setRemoteDescription: Error Failed to set remote offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answe

### ISSUE THREAD

**Issue by maheshlalu** [cloudwebrtc/dart-sip-ua#46]
emit "peerconnection:setremotedescriptionfailed" [error:Unable to RTCPeerConnection::setRemoteDescription: Error Failed to set remote offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer.]<…> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type 'TypeError' is not a subtype of type 'String'

**Comment by cloudwebrtc** [comment]
@maheshlalu Please modify the title to a short problem description instead of a large error log, which will help solve the problem.

**Comment by cloudwebrtc** [comment]
Still an SDP negotiation issue.
