### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))

### ISSUE THREAD

**Issue by maheshlalu** [cloudwebrtc/dart-sip-ua#47]
only in Android.

**Comment by cloudwebrtc** [comment]
Please check your SSL certificate.

**Comment by maheshlalu** [comment]
it's working in iOS. What is difference. kindle check once.

**Comment by maheshlalu** [comment]
@cloudwebrtc pls update on it.

**Comment by maheshlalu** [comment]
@cloudwebrtc pls update on it.

**Comment by maheshlalu** [comment]
Fixed the issue I have commented the code in WebSocket_dart_imp.dart file
// _socket =
      //     await WebSocket.connect(_url, protocols: protocols, headers: headers);

      /// Allow self-signed certificate, for test only.
       var parsed_url = Grammar.parse(this._url, 'absoluteURI');
       _socket = await _connectForBadCertificate(parsed_url.scheme, parsed_url.host, parsed_url.port);

@cloudwebrtc please explain me what difference between connect and connectForBadCertificate methods.

**Comment by maheshlalu** [comment]
@cloudwebrtc please update on it.
