### ISSUE TITLE
Unable to receive calls

### ISSUE THREAD

**Issue by wilkomanger** [cloudwebrtc/dart-sip-ua#48]
Hi, this is probably not enough information, but maybe you can point me into the right direction. When I receive a call, everything goes through up till `ACK`, until the call immediately gets canceled with a `BYE`, and these notable headers:
```
X-Asterisk-HangupCause: Bearer capability not available
X-Asterisk-HangupCauseCode: 58
```
Any idea what the reason could be? Thanks!

**Comment by cloudwebrtc** [comment]
It is recommended that you use a packet capture tool to analyze the SIP signaling process, and especially observe the errors displayed on the Asterisk console.

**Comment by wilkomanger** [comment]
Yes, it was something on our end.
