### ISSUE TITLE
Add ability to load WebRTC dynamically on demand

### ISSUE THREAD

**Issue by wilkomanger** [cloudwebrtc/dart-sip-ua#51]
Hi, we have the use case that an FCM notification will wake up the app to accept a call. Now, because of the WebRTC loading time, when the app is terminated it takes too long to start up again, and the call can't be accepted anymore.

After removing the dart-sip-ua dependency the loading time is fine again. So a fix might be to load the WebRTC library on demand, or perhaps something else.

Thanks!

**Comment by cloudwebrtc** [comment]
Do you know where it is stuck, and how long does it usually block? Normally webrtc loading is sub-second.

**Comment by wilkomanger** [comment]
It seems that running in profile (and probably then also release mode) it loads quickly enough. Still interesting to keep in mind though.

I do have some other issues though, is there an example of picking up a call? Especially in the background? I've only made it work by automatically `answer` when the call state is `PROGRESS`.
