### ISSUE TITLE
emit "peerconnection:setremotedescriptionfailed" [error:InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: kStable]

### ISSUE THREAD

**Issue by maheshlalu** [cloudwebrtc/dart-sip-ua#53]
emit "peerconnection:setremotedescriptionfailed" [error:InvalidStateError: Failed
to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: kStable]

Working in both android and iOS but in chrome not working.

**Comment by cloudwebrtc** [comment]
Please use the bug report template.
https://github.com/cloudwebrtc/dart-sip-ua/issues/new?assignees=&labels=bug&template=bug_report.md&title=

Without comprehensive information and steps to reproduce, it does not help locate the bug.
