### ISSUE TITLE
Not working on LTE mobile data

### ISSUE THREAD

**Issue by nisal-rumex** [cloudwebrtc/dart-sip-ua#57]
**Describe the bug**
I connected one mobile device to WIFI connection and other device to mobile data. Then I make a call and accept from the other end. Signaling is working fine, but streaming is not happening. The same issue was reported in [flutter webRTC](https://github.com/cloudwebrtc/flutter-webrtc-demo/issues/46) repository also. As described in there I used 'viagenie' turn server and tried. But it still failing. Please give this a look.

**To Reproduce**
1. Get two devices. Connect one device with WIFI and the other device with mobile data.
2. Then make a call from one end and you will see streaming is not happening.

**Comment by glennmichaelmejias** [comment]
having the same problem here.

**Comment by ghenry** [comment]
Looks like it was sorted in that issue. Closing this.
