### ISSUE TITLE
What is dart based endpoint of this project

### ISSUE THREAD

**Issue by codepie3** [cloudwebrtc/dart-sip-ua#63]
**Describe the bug**
I am not able to find proper dart  with main function endpoint to resolve it

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ' Run Debug Configuration ' 
2. Click on flutter '' then select Name class it as you want , below you will get option to set endpoint of dart.
3. You will get dialog with 2 tab select class or search dart endpoint 
4. Error dart class don't have main function

**Expected behaviour**
A class must be name friendly to find  proper dart endpoints

**System Information()**
Flutter SDK Version:
Target OS and Version:Android 10 , IOS 13.1
Host OS and Version:Ubuntu 18 LTS

**Comment by ghenry** [comment]
Hi codepie3,

Did you read the guide to get set up? I don't think you have.

Please come back with more info.

Thanks.
