### ISSUE TITLE
UI and Some functionality related changes required.

### ISSUE THREAD

**Issue by tjramoliya** [cloudwebrtc/dart-sip-ua#65]
@cloudwebrtc  
Hello cloudwebrtc community,

We have checked this demo by installing in android and iOS Device and we have also configured server.
We have checked your demo all functionality working properly related to SIP call and video call.

But i have some suggestion to improve this demo. 
1. Sometime UI not responsible and hangup in some screens.
2. When i start to call another user, timer will start automatically before call pick up, in that place you have to place in progress call or something like that.
3. When we try one to one call sometimes registration issues are there, you need to registered again.

So i have hope you will implement my suggestion in your current demo. It will help many users who are using this demo.

Thanks
Tushar Ramoliya
Ecosmob Technology Pvt. Ltd.

**Comment by ghenry** [comment]
Thanks!

This is an open source project. Patches welcome.
