### ISSUE TITLE
Code: [488], Cause: Bad Media Description, Reason: Not Acceptable Here

### ISSUE THREAD

**Issue by chikondot** [cloudwebrtc/dart-sip-ua#72]
Good day,

Having an issue with setting up the client to setup calls.
Call goes through as indicated in file attached, but dart-ua-sip works for est. 2 Seconds then client returns [488] 

testing on tryit.jssip.net works perfectly
Where could the problem be?

SIPTRACE:
https://pastebin.com/fzPR1y6V

**Comment by cloudwebrtc** [comment]
@chikondot I read your logs, I think you can analyze from FreeSWITCH's server logs, it is most likely that the SDP negotiation failed

**Comment by chikondot** [comment]
@cloudwebrtc we have RTPengine running in the middle handling SDP and it seems to be reporting no error. the termination (BYE) seems to be generated from client.

If possible may you provide example of what SDP should look like between client and RTPengine and Freeswitch
