### ISSUE TITLE
Uncaught Unable to getUserMedia: NoSuchMethodError: method not found: 'getUserMedia' (a.getUserMedia is not a function)

### ISSUE THREAD

**Issue by olegshentz1** [cloudwebrtc/dart-sip-ua#75]
@cloudwebrtc 
Hello cloudwebrtc community,

When I build the app for web release using `flutter build web` command, connect to webrtc server and try to call I get error:

In Chrome browser:
> Uncaught Unable to getUserMedia: NoSuchMethodError: method not found: 'getUserMedia' (a.getUserMedia is not a function)

In FireFox browser:

> Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_helper.dart

In debug mode everything works fine.

**Stack Trace:**

> Uncaught Unable to getUserMedia: NoSuchMethodError: method not found: 'getUserMedia' (a.getUserMedia is not a function)
>     at Object.e (http://app.x2one.com/main.dart.js:1980:3)
>     at http://app.x2one.com/main.dart.js:70343:9
>     at age.a (http://app.x2one.com/main.dart.js:3322:72)
>     at age.$2 (http://app.x2one.com/main.dart.js:26036:23)
>     at afA.$2 (http://app.x2one.com/main.dart.js:26031:25)
>     at Om.C1 (http://app.x2one.com/main.dart.js:27060:42)
>     at Om.C0 (http://app.x2one.com/main.dart.js:27062:32)
>     at ns.a9e (http://app.x2one.com/main.dart.js:26241:23)
>     at ab3.$0 (http://app.x2one.com/main.dart.js:26402:7)
>     at Object.r3 (http://app.x2one.com/main.dart.js:3429:82)

**Comment by ghenry** [comment]
Hi,

This only works under HTTPS as WebRTC isn't allowed otherwise. That's why calls to the core browser APIs are failing. 

Thanks.

**Comment by olegshentz1** [comment]
Is it basically mean that when I deploy my application to server it doesn't work under HTTPS ? Сould there be a problem in using incorrect certificate on the server? 
Because when I run application locally via Chrome browser everything work fine.

**Comment by ghenry** [comment]
> @ghenry thanks for response,
> 
> Is it basically mean that when I deploy my application to server it doesn't work under HTTPS ? Сould there be a problem in using incorrect certificate on the server?
> Because when I run application locally via Chrome browser everything work fine.

See my the second note here:

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

"Note: If the current document isn't loaded securely, navigator.mediaDevices will be undefined, and you cannot use getUserMedia(). See Security for more information on this and other security issues related to using getUserMedia()."

Anything WebRTC needs to be loaded via HTTPS in order for client side code to access the getUserMedia API call in a browser.

localhost on chrome works.

https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https

Not a bug with our code. User error :-)

Closing issue. Thanks for using!
