### ISSUE TITLE
Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)

### ISSUE THREAD

**Issue by olegshentz1** [cloudwebrtc/dart-sip-ua#76]
@cloudwebrtc
Hello cloudwebrtc community,

Sometime when connect to webrtc server in android application and try to call I get this error(usually in  in OUTGOING state):

**Stack Trace:**

> I/flutter (10382): ##### callState.state =>  CallStateEnum.STREAM # OUTGOING
> I/org.webrtc.Logging(10382): WebRtcAudioRecordExternal: enableBuiltInAEC(false)
> I/org.webrtc.Logging(10382): WebRtcAudioEffectsExternal: setAEC(false)
> I/org.webrtc.Logging(10382): WebRtcAudioRecordExternal: enableBuiltInNS(true)
> I/org.webrtc.Logging(10382): WebRtcAudioEffectsExternal: setNS(true)
> I/org.webrtc.Logging(10382): NetworkMonitor: Start monitoring with native observer 540770774080
> I/flutter (10382): MediaStreamTrack:enableSpeakerphone false
> W/org.webrtc.Logging(10382): NetworkMonitorAutoDetect: Unable to obtain permission to request a cellular network.
> I/org.webrtc.Logging(10382): NetworkMonitorAutoDetect: Network becomes available: 100
> D/FlutterWebRTCPlugin(10382): onIceGatheringChangeGATHERING
> D/FlutterWebRTCPlugin(10382): peerConnectionSetLocalDescription() end
> I/org.webrtc.Logging(10382): NetworkMonitorAutoDetect: capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&FOREGROUND LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -45]
> E/MethodChannel#FlutterWebRTC.Method(10382): Failed to handle method call
> E/MethodChannel#FlutterWebRTC.Method(10382): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.onMethodCall(FlutterWebRTCPlugin.java:358)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at android.os.MessageQueue.next(MessageQueue.java:325)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at android.os.Looper.loop(Looper.java:142)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
> E/MethodChannel#FlutterWebRTC.Method(10382): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> I/org.webrtc.Logging(10382): NetworkMonitorAutoDetect: link properties changed: {InterfaceName: wlan0 LinkAddresses: [fe80::20a:f5ff:feb5:bea4/64,192.168.97.40/20,]  Routes: [fe80::/64 -> :: wlan0,192.168.96.0/20 -> 0.0.0.0 wlan0,0.0.0.0/0 -> 192.168.96.254 wlan0,] DnsAddresses: [8.8.8.8,] Domains: null MTU: 0 TcpBufferSizes: 524288,2097152,4194304,262144,524288,1048576}
> D/FlutterWebRTCPlugin(10382): onIceCandidate
> I/chatty  (10382): uid=10981(pdac.oleg.widely_app) signaling_threa identical 1 line
> D/FlutterWebRTCPlugin(10382): onIceCandidate
> E/flutter (10382): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
> E/flutter (10382): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
> E/flutter (10382): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
> E/flutter (10382): <asynchronous suspension>
> E/flutter (10382): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
> E/flutter (10382): #3      RTCVideoRenderer.srcObject= (package:flutter_webrtc/rtc_video_view.dart:66:14)
> E/flutter (10382): #4      WebrtcBloc._handelStreams (package:widely_app/blocs/webrtcbloc/webrtc_bloc.dart:324:24)
> E/flutter (10382): #5      WebrtcBloc.callStateChanged (package:widely_app/blocs/webrtcbloc/webrtc_bloc.dart:135:9)
> E/flutter (10382): #6      SIPUAHelper._notifyCallStateListeners.<anonymous closure> (package:sip_ua/src/sip_ua_helper.dart:388:16)
> E/flutter (10382): #7      SetMixin.forEach (dart:collection/set.dart:148:30)
> E/flutter (10382): #8      SIPUAHelper._notifyCallStateListeners (package:sip_ua/src/sip_ua_helper.dart:387:27)
> E/flutter (10382): #9      SIPUAHelper._options.<anonymous closure>.<anonymous closure> (package:sip_ua/src/sip_ua_helper.dart:258:9)
> E/flutter (10382): #10     _rootRun (dart:async/zone.dart:1122:38)
> E/flutter (10382): #11     _CustomZone.run (dart:async/zone.dart:1023:19)
> E/flutter (10382): #12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
> E/flutter (10382): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
> E/flutter (10382): #14     _rootRun (dart:async/zone.dart:1126:13)
> E/flutter (10382): #15     _CustomZone.run (dart:async/zone.dart:1023:19)
> E/flutter (10382): #16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
> E/flutter (10382): #17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
> E/flutter (10382): #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
> E/flutter (10382): #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
> E/flutter (10382): #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> E/flutter (10382): 
> D/FlutterWebRTCPlugin(10382): onIceCandidate
> I/chatty  (10382): uid=10981(pdac.oleg.widely_app) signaling_threa identical 2 lines
> D/FlutterWebRTCPlugin(10382): onIceCandidate
> I/flutter (10382): [2020-04-22 16:19:00.514] Level.debug rtc_session.dart:1620 ::: emit "sdp"
> I/flutter (10382): [2020-04-22 16:19:00.522] Level.debug rtc_session.dart:2192 ::: emit "sending" [request]
> I/flutter (10382): [2020-04-22 16:19:00.537] Level.debug transport.dart:167 ::: send()
> I/flutter (10382): [2020-04-22 16:19:00.546] Level.debug transport.dart:178 ::: sending message:

**Comment by ghenry** [comment]
Hi,

Can you create a new issue with the Bug template please. There's not enough context here.

Thanks.
