### ISSUE TITLE
Is there an easy way to change SDP using SIPUAHelper?

### ISSUE THREAD

**Issue by cheluskin** [cloudwebrtc/dart-sip-ua#77]
Hi. I need to change sdp. Fix one line, but it is impossible to do this on the server. Please tell me if there is just a way to do this using an example

**Comment by cloudwebrtc** [comment]
https://github.com/cloudwebrtc/dart-sdp-transform
You can use the above project to replace SDP before INVITE in the rtc_session.dart file.
