### ISSUE TITLE
Use without registration

### ISSUE THREAD

**Issue by sebastiantoro** [cloudwebrtc/dart-sip-ua#83]
There are multiple SIP clients that can be used without registering to a SIP server first, meaning that they can make a SIP call to any URI without the need of being registered into a SIP Server. In the example project, the app requieres registration before any calls can be made (as shown in the instructions). So my questions are: 
1. Is it possible to make SIP calls without having to register into a SIP server?
2. If it is, what changes should be done to the example for this to work?

**Comment by cloudwebrtc** [comment]
Theoretically supportable, just don't send REGISTER message
The www-authentication process remains unchanged when sending INVITE.

You can try to add bool send_register in [UaSettings](https://github.com/cloudwebrtc/dart-sip-ua/blob/master/lib/src/sip_ua_helper.dart#L459) parameter, and pass it to [Settings](https://github.com/cloudwebrtc/dart-sip-ua/blob/master/lib/src/config.dart#L40)

**Comment by ecilliyuz** [comment]
Is there a solution to this now?
How can we make calls between devices on the same network without a SIP server?
