### ISSUE TITLE
Call fails with Asterisk 16 -> Reason: SIP ;cause=488; text="Not Acceptable Here"

### ISSUE THREAD

**Issue by rlsutton1** [cloudwebrtc/dart-sip-ua#9]
Call fails with Asterisk 16 -> Reason: SIP ;cause=488; text="Not Acceptable Here"

Asterisk and Flutter logs attached with full SIP trace.

This change in RTCSession.dart fixes this, but is just a hack and a proper fix is required.
> //TODO: Commented out because this seems to cause errors with Asterisk
> 
> //await this._connection.setRemoteDescription(answer);

this line in the logs is important:

> I/flutter (15658): 09:12:30.029 (+0:00:29.733517) [DartSIP:RTCSession] ERROR: emit "peerconnection:setremotedescriptionfailed" [error:Unable to RTCPeerConnection::setRemoteDescription: Failed to set remote answer sdp: Called in wrong state: kStable]

[Asterisk16-5PjSip.log](https://github.com/cloudwebrtc/dart-sip-ua/files/3655284/Asterisk16-5PjSip.log)

[DartSipUaDemo.log](https://github.com/cloudwebrtc/dart-sip-ua/files/3655286/DartSipUaDemo.log)

**Comment by cloudwebrtc** [comment]
@rlsutton1 I made a patch on this PR https://github.com/cloudwebrtc/dart-sip-ua/pull/11, can you try it? Because I don't have an Asterisk server to do the test.

**Comment by ghenry** [comment]
Thanks for the help testing and bug reporting @rlsutton1

**Comment by cloudwebrtc** [comment]
Fixed.
