### ISSUE TITLE
Can't register on chrome

### ISSUE THREAD

**Issue by sababuvercetti** [cloudwebrtc/dart-sip-ua#94]
I recently faced an issue where I couldn't register on the browser yet  I could on my phone. 
Retuens an error saying websocket connection failed
![socket](https://user-images.githubusercontent.com/35136541/84734748-6579be80-afaa-11ea-9954-d879e0524a48.png)

**Comment by cloudwebrtc** [comment]
Because Chrome cannot set the Origin Header, you cannot connect to tryit.jssip.net locally, but you can connect to the local sip wss server.

**Comment by sababuvercetti** [comment]
Thanks
