### ISSUE TITLE
sip_ua_helper.SendMessage Issues

### ISSUE THREAD

**Issue by wangzhenzhe** [cloudwebrtc/dart-sip-ua#96]
**Describe the bug**
The VoIP call works well and I like this library.
I have tried using the sip message of this library and I met an exception caught.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'URI' is not a subtype of type 'String'

**To Reproduce**
The sip_ua version was 0.2.1
1. A successful connected SIP session
2. Call sip_ua_helper.sendMessage(String target, String body, options) as
 widget.helper.sendMessage("100", "Hello World");

The target "100" was a callable extension user in my environment.

3. You could see the exception caught
type 'URI' is not a subtype of type 'String'

**Expected behavior**
I found this exception was because
message.dart line 58
// Check target validity.
target = this._ua.normalizeTarget(target);
The var target was a String but normalizeTarget(target) will return URI.
I thought it was easy issue to fix it.

BUT why this simple issue had not been reported before, is there nobody concern about message features and nobody use sendMessage? Interesting!
I thought it would be better to add message usage to example of this library.
Anyway, this library is a good job. Thanks!

**System Infomation()**
Flutter SDK Version: 1.190-4.1.pre
Target OS and Version: Android 29.0.3
Host OS and Version: Windows 10 Version 10.0.18363.900

The version of sip_ua was added.

**Comment by wangzhenzhe** [comment]
Today I tried to use this library on SIP text message. 

Actually I got surprised that only sendMessage was supported in this library and the sip_ua_helper has not listened to message event.
There were some other problems such as UTF8 content length and SIP message reply.
But thanks to the good SIP protocol implementation, it was not very difficult to add listener and make UTF8 messages sent. I had made some improvements on this sip_ua library to support message operations.
I would like to contribute and share my improvement if the owner like.

**Comment by cloudwebrtc** [comment]
@wangzhenzhe Thank you, I am very happy to accept PR.

**Comment by wangzhenzhe** [comment]
> @wangzhenzhe Thank you, I am very happy to accept PR.

Thanks. Give me some time to make the code changes more clear and easy to understand.
I will make a PR after it is done.

**Comment by wangzhenzhe** [comment]
@cloudwebrtc 
May I have the previlige to publish new branch to this project to make a new Pull Request to you?

**Comment by cloudwebrtc** [comment]
@wangzhenzhe You can fork this project and create PR after patching.

**Comment by wangzhenzhe** [comment]
> @wangzhenzhe You can fork this project and create PR after patching.
Hi, I had pushed my code changes and opened the Pull Request as below. Please take a look and test it in example. The dail pad screen will show the incoming text message after registered. Please contact me if you have any comments or questions.

Add SIP message listener to listen the new incoming SIP text message #97

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/dart-sip-ua/pull/97/commits/db68c758a99d1e7b41e3b3e1336dacda90e00b69
