### ISSUE TITLE
html_dart2js.dart:31569 WebSocket connection to 'wss://tryit.jssip.net:10443/' failed: Error during WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by sababuvercetti** [cloudwebrtc/dart-sip-ua#98]
**Describe the bug**

**To Reproduce**

Try to register on chrome

**Expected behavior**
Registration fails

**System Infomation()**
Flutter SDK Version:1.18
Target OS and Version: Chrome

**Comment by cloudwebrtc** [comment]
duplicate https://github.com/cloudwebrtc/dart-sip-ua/issues/94
