### ISSUE TITLE
web注册正常，mobile Registration Failed 

### ISSUE THREAD

**Issue by cmtj199337** [cloudwebrtc/dart-sip-ua#99]
我猜想原因有可能是因为sip url用了ip地址，而不是域名。
有这种情况吗？

**Comment by cloudwebrtc** [comment]
通常不会，mobile 上可以直接使用ip注册的。

**Comment by cmtj199337** [comment]
![88302275](https://user-images.githubusercontent.com/15863833/87038333-2690fe80-c220-11ea-816d-957793f26f93.png)
测了很久一直卡在这儿，能帮我定位一下问题吗？

**Comment by cloudwebrtc** [comment]
您应该从服务器端定位，因为您的日志显示Websocket 连接已经成功.

**Comment by cmtj199337** [comment]
好的，谢谢，我先关闭这个issue了。定位到问题我过来留解决方法。
